name: RDP Access Workflow

on: [push]

jobs:
  build:
    runs-on: windows-latest
    steps:
    - name: Download ngrok
      run: |
        curl -O https://bin.equinox.io/c/4VmDzA7iaHb/ngrok-stable-linux-amd64.zip
        unzip ngrok-stable-linux-amd64.zip
        chmod +x ngrok

    - name: Add ngrok to PATH
      run: echo "${GITHUB_WORKSPACE}" >> $GITHUB_PATH

    - name: Start ngrok
      run: |
        ./ngrok authtoken 1ynqMXNZqPHZFJsrK6oJhkOJDgL_7zkwHGXMRfXwSzABCDEF
        ./ngrok tcp 3389 --log=stdout > ngrok.log &
      env:
        NGROK_AUTHTOKEN: 1ynqMXNZqPHZFJsrK6oJhkOJDgL_7zkwHGXMRfXwSzABCDEF

    - name: Get ngrok public URL
      run: |
        sleep 5
        NGROK_PUBLIC_URL=$(grep -o 'tcp://[^[:space:]]*' ngrok.log | sed 's/tcp:\/\///')
        echo "NGROK_PUBLIC_URL=$NGROK_PUBLIC_URL" >> $GITHUB_ENV

    - name: Enable RDP
      run: |
        Set-ItemProperty -Path 'HKLM:\System\CurrentControlSet\Control\Terminal Server' -Name "fDenyTSConnections" -Value 0
        Enable-NetFirewallRule -DisplayGroup "Remote Desktop"
      shell: pwsh

    - name: Set RDP password
      run: |
        Set-LocalUser -Name "runneradmin" -Password (ConvertTo-SecureString -AsPlainText "P@ssw0rd!" -Force)
      shell: pwsh

    - name: Output RDP connection details
      run: |
        echo "RDP is now available at ${{ env.NGROK_PUBLIC_URL }}"
        echo "Username: runneradmin"
        echo "Password: P@ssw0rd!"

    # Add your other workflow steps here
