name: Linux RDP Tunnel

on: [push, workflow_dispatch]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Install Required Packages
      run: |
        sudo apt-get update
        sudo apt-get install -y xrdp xfce4 xfce4-goodies
        sudo systemctl enable xrdp
        sudo systemctl start xrdp
        # Allow RDP traffic on port 3390 instead of 3389
        sudo sed -i 's/3389/3390/g' /etc/xrdp/xrdp.ini
        sudo systemctl restart xrdp
        sudo ufw allow 3390/tcp

    - name: Create and Configure RDP User
      run: |
        sudo useradd -m rdpuser -s /bin/bash
        echo "rdpuser:P@ssw0rd!" | sudo chpasswd
        sudo adduser rdpuser sudo
        
    - name: Set XFCE as Default Session
      run: |
        echo xfce4-session >~/.xsession
        sudo service xrdp restart
        
    - name: Start SSH Tunnel for Linux RDP
      shell: bash
      run: |
        echo "Starting SSH tunnel for Linux RDP..."
        ssh -o StrictHostKeyChecking=no -T -R 3390:localhost:3390 serveo.net > serveo_output.txt 2>&1 &
        sleep 10  # Allow time for the tunnel to establish
        cat serveo_output.txt

    - name: Simulate Stuck Behavior for 1 Day
      run: |
        echo "Simulating stuck tunnel for 1 Day..."
        sleep 86400
