name: RDP Access Workflow with Serveo and Performance Optimizations

on: [push]

jobs:
  build:
    runs-on: windows-latest
    steps:
    - name: Install OpenSSH
      run: |
        Add-WindowsCapability -Online -Name OpenSSH.Client~~~~0.0.1.0
      shell: powershell

    - name: Enable RDP and Optimize Performance
      run: |
        Set-ItemProperty -Path 'HKLM:\System\CurrentControlSet\Control\Terminal Server' -Name "fDenyTSConnections" -Value 0
        Enable-NetFirewallRule -DisplayGroup "Remote Desktop"
        
        # Disable visual effects for performance
        Set-ItemProperty -Path 'HKCU:\Software\Microsoft\Windows\CurrentVersion\Explorer\VisualEffects' -Name 'VisualFXSetting' -Value 2
        
        # Set power plan to high performance
        powercfg /setactive 8c5e7fda-e8bf-4a96-9a85-a6e23a8c635c
        
        # Disable unnecessary services
        Stop-Service -Name "SysMain" -Force
        Set-Service -Name "SysMain" -StartupType Disabled
        
        # Disable Windows Search indexing
        Set-Service WSearch -StartupType Disabled
        Stop-Service WSearch
      shell: powershell

    - name: Set RDP password
      run: |
        Set-LocalUser -Name "runneradmin" -Password (ConvertTo-SecureString -AsPlainText "P@ssw0rd!" -Force)
      shell: powershell

    - name: Create Serveo tunnel
      run: |
        $job = Start-Job -ScriptBlock {
          ssh -o StrictHostKeyChecking=no -R 80:localhost:3389 serveo.net
        }
        Start-Sleep -Seconds 10
        $output = Receive-Job $job
        $serveoUrl = ($output | Select-String -Pattern "Forwarding.*tcp://(.*)").Matches.Groups[1].Value
        echo "SERVEO_URL=$serveoUrl" | Out-File -FilePath $env:GITHUB_ENV -Encoding utf8 -Append
        Write-Host "Serveo URL: $serveoUrl"
      shell: powershell

    - name: Output RDP connection details
      run: |
        if ($env:SERVEO_URL) {
          Write-Host "RDP is now available at $env:SERVEO_URL"
        } else {
          Write-Host "Failed to retrieve Serveo URL"
        }
        Write-Host "Username: runneradmin"
        Write-Host "Password: P@ssw0rd!"
      shell: powershell

    - name: Optimize RDP settings
      run: |
        # Set RDP to prefer performance over appearance
        reg add "HKEY_CURRENT_USER\Software\Microsoft\Windows\CurrentVersion\Explorer\VisualEffects" /v VisualFXSetting /t REG_DWORD /d 2 /f
        
        # Disable desktop composition
        reg add "HKEY_CURRENT_USER\Software\Microsoft\Windows\DWM" /v CompositionPolicy /t REG_DWORD /d 0 /f
        
        # Disable full window dragging
        reg add "HKEY_CURRENT_USER\Control Panel\Desktop" /v DragFullWindows /t REG_SZ /d 0 /f
        
        # Disable cursor shadow
        reg add "HKEY_CURRENT_USER\Software\Microsoft\Windows\CurrentVersion\Explorer\Advanced" /v DisableCursorShadow /t REG_DWORD /d 1 /f
        
        # Disable font smoothing
        reg add "HKEY_CURRENT_USER\Control Panel\Desktop" /v FontSmoothing /t REG_SZ /d 0 /f
      shell: powershell

    - name: Keep alive
      run: |
        $i = 0
        while ($true) {
          Write-Host "Keeping session alive - $i"
          Start-Sleep -Seconds 600
          $i++
        }
      shell: powershell
