name: RDP Tunnel

on: [push, workflow_dispatch]

jobs:
  build:
    runs-on: windows-latest

    steps:
    - name: Enable RDP and Configure Windows
      run: |
        # Enable Remote Desktop and configure firewall
        Set-ItemProperty -Path 'HKLM:\System\CurrentControlSet\Control\Terminal Server' -Name "fDenyTSConnections" -Value 0
        Enable-NetFirewallRule -DisplayGroup "Remote Desktop"
        # Set up RDP user account
        Set-LocalUser -Name "runneradmin" -Password (ConvertTo-SecureString -AsPlainText "P@ssw0rd!" -Force)
        Restart-Service termservice -Force

    - name: Install Cloudflare Tunnel
      run: |
        # Download and install Cloudflare Tunnel
        Invoke-WebRequest -Uri https://github.com/cloudflare/cloudflared/releases/latest/download/cloudflared-windows-amd64.zip -OutFile cloudflared.zip
        Expand-Archive -Path cloudflared.zip -DestinationPath $env:USERPROFILE\cloudflared
        Remove-Item -Path cloudflared.zip
        $env:PATH += ";$env:USERPROFILE\cloudflared"

    - name: Authenticate Cloudflare Tunnel
      run: |
        # Authenticate Cloudflare Tunnel (this will open a browser window for authentication)
        cloudflared login

    - name: Create Cloudflare Tunnel
      run: |
        # Create a new Cloudflare Tunnel
        cloudflared tunnel create my-rdp-tunnel

    - name: Configure Tunnel
      run: |
        # Create a configuration file for the tunnel
        $config = @"
        tunnel: my-rdp-tunnel
        credentials-file: $env:USERPROFILE\.cloudflared\my-rdp-tunnel.json
        ingress:
          - hostname: rdp.example.com
            service: tcp://localhost:3389
          - service: http_status:404
        "@
        Set-Content -Path "$env:USERPROFILE\.cloudflared\config.yml" -Value $config

    - name: Run Cloudflare Tunnel
      run: |
        # Start the Cloudflare Tunnel
        cloudflared tunnel run my-rdp-tunnel

    - name: Simulate Stuck Behavior for 100 Minutes
      run: |
        Write-Host "Simulating stuck tunnel for 100 minutes..."
        Start-Sleep -Seconds 6000
