name: Free Windows RDP with SSD

on:
  workflow_dispatch:

jobs:
  rdp-job:
    runs-on: windows-latest  # Windows GitHub runner, backed by SSD
    steps:
      - name: Set up SSH keys for Serveo tunneling
        run: |
          mkdir $env:USERPROFILE\.ssh
          ssh-keygen -t rsa -N "" -f $env:USERPROFILE\.ssh\id_rsa
          echo "Host serveo.net\n\tStrictHostKeyChecking no\n" >> $env:USERPROFILE\.ssh\config

      - name: Enable RDP and open firewall
        run: |
          # Enable RDP on the Windows machine
          Set-ItemProperty -Path 'HKLM:\System\CurrentControlSet\Control\Terminal Server' -name "fDenyTSConnections" -Value 0
          
          # Allow RDP through the Windows firewall
          netsh advfirewall firewall set rule group="remote desktop" new enable=Yes
          
          # Set a password for the current user (use a strong password here)
          $password = ConvertTo-SecureString 'YourPassword123!' -AsPlainText -Force
          $user = [System.Security.Principal.WindowsIdentity]::GetCurrent().Name
          Set-LocalUser -Name $user -Password $password

      - name: Start Serveo tunnel for RDP
        run: |
          # Start Serveo tunnel for port 3389 (RDP port)
          Start-Process -NoNewWindow powershell -ArgumentList '-NoProfile -ExecutionPolicy Bypass -Command "ssh -R 3389:localhost:3389 serveo.net"'

      - name: Get Serveo tunnel URL
        run: |
          Start-Sleep -Seconds 5
          # Display the Serveo public URL for the RDP connection
          Write-Host "Your RDP connection URL is: https://serveo.net:3389"
