name: RDP Tunnel

on: [push, workflow_dispatch]

jobs:
  build:
    runs-on: windows-latest

    steps:
    - name: Enable RDP and Configure Windows
      run: |
        # Enable Remote Desktop and configure firewall
        Set-ItemProperty -Path 'HKLM:\System\CurrentControlSet\Control\Terminal Server' -Name "fDenyTSConnections" -Value 0
        Enable-NetFirewallRule -DisplayGroup "Remote Desktop"
        # Set up RDP user account
        Set-LocalUser -Name "runneradmin" -Password (ConvertTo-SecureString -AsPlainText "P@ssw0rd!" -Force)
        Restart-Service termservice -Force

    - name: Install ngrok
      run: |
        Invoke-WebRequest -Uri https://bin.equinox.io/c/4v2PAdc6RUQ/ngrok-stable-windows-amd64.zip -OutFile ngrok.zip
        Expand-Archive -Path ngrok.zip -DestinationPath $env:USERPROFILE\ngrok
        Remove-Item -Path ngrok.zip
        $env:PATH += ";$env:USERPROFILE\ngrok"

    - name: Authenticate ngrok
      run: |
        echo "Authenticating ngrok..."
        ngrok authtoken YOUR_AUTH_TOKEN

    - name: Start ngrok Tunnel for RDP
      shell: bash
      run: |
        echo "Starting ngrok tunnel..."
        ngrok tcp 3389 > ngrok_output.txt 2>&1 &
        sleep 10  # Allow time for the tunnel to establish
        # Output the ngrok tunnel URL for verification
        cat ngrok_output.txt

    - name: Simulate Stuck Behavior for 100 Minutes
      run: |
        Write-Host "Simulating stuck tunnel for 100 minutes..."
        Start-Sleep -Seconds 6000
