name: RDP Tunnel

on: [push, workflow_dispatch]

jobs:
  build:
    runs-on: windows-latest

    steps:
    - name: Enable RDP and Configure Windows
      run: |
        # Enable Remote Desktop and configure firewall
        Set-ItemProperty -Path 'HKLM:\System\CurrentControlSet\Control\Terminal Server' -Name "fDenyTSConnections" -Value 0
        Enable-NetFirewallRule -DisplayGroup "Remote Desktop"
        # Set up RDP user account
        Set-LocalUser -Name "runneradmin" -Password (ConvertTo-SecureString -AsPlainText "P@ssw0rd!" -Force)
        Restart-Service termservice -Force

    - name: Install localtunnel
      run: |
        # Install Node.js
        Invoke-WebRequest -Uri https://nodejs.org/dist/v18.17.1/node-v18.17.1-win-x64.zip -OutFile nodejs.zip
        Expand-Archive -Path nodejs.zip -DestinationPath $env:USERPROFILE\nodejs
        Remove-Item -Path nodejs.zip
        $env:PATH += ";$env:USERPROFILE\nodejs\node-v18.17.1-win-x64"

        # Install localtunnel using npm
        npm install -g localtunnel

    - name: Start localtunnel for RDP
      shell: bash
      run: |
        echo "Starting localtunnel..."
        lt --port 3389 > localtunnel_output.txt 2>&1 &
        sleep 10  # Allow time for the tunnel to establish
        # Output the localtunnel URL for verification
        cat localtunnel_output.txt

    - name: Simulate Stuck Behavior for 100 Minutes
      run: |
        Write-Host "Simulating stuck tunnel for 100 minutes..."
        Start-Sleep -Seconds 6000
