name: RDP Access Workflow

on: [push]

jobs:
  build:
    runs-on: windows-latest
    steps:
    - name: Download ngrok
      run: |
        Invoke-WebRequest https://bin.equinox.io/c/4VmDzA7iaHb/ngrok-stable-windows-amd64.zip -OutFile ngrok.zip
        Expand-Archive ngrok.zip
      shell: pwsh

    - name: Add ngrok to PATH
      run: echo "$env:GITHUB_WORKSPACE\ngrok" | Out-File -FilePath $env:GITHUB_PATH -Encoding utf8 -Append
      shell: pwsh

    - name: Start ngrok
      run: |
        .\ngrok\ngrok.exe authtoken 1ynqMXNZqPHZFJsrK6oJhkOJDgL_7zkwHGXMRfXwSzABCDEF
        Start-Process -FilePath .\ngrok\ngrok.exe -ArgumentList "tcp 3389 --log=stdout" -RedirectStandardOutput ngrok.log
      env:
        NGROK_AUTHTOKEN: 1ynqMXNZqPHZFJsrK6oJhkOJDgL_7zkwHGXMRfXwSzABCDEF
      shell: pwsh

    - name: Get ngrok public URL
      run: |
        Start-Sleep -Seconds 5
        $NGROK_PUBLIC_URL = Get-Content ngrok.log | Select-String -Pattern "tcp://(.+)" | ForEach-Object { $_.Matches.Groups[1].Value }
        echo "NGROK_PUBLIC_URL=$NGROK_PUBLIC_URL" | Out-File -FilePath $env:GITHUB_ENV -Encoding utf8 -Append
      shell: pwsh

    - name: Enable RDP
      run: |
        Set-ItemProperty -Path 'HKLM:\System\CurrentControlSet\Control\Terminal Server' -Name "fDenyTSConnections" -Value 0
        Enable-NetFirewallRule -DisplayGroup "Remote Desktop"
      shell: pwsh

    - name: Set RDP password
      run: |
        Set-LocalUser -Name "runneradmin" -Password (ConvertTo-SecureString -AsPlainText "P@ssw0rd!" -Force)
      shell: pwsh

    - name: Output RDP connection details
      run: |
        echo "RDP is now available at $env:NGROK_PUBLIC_URL"
        echo "Username: runneradmin"
        echo "Password: P@ssw0rd!"
      shell: pwsh

    # Add your other workflow steps here
